Rename private function Container::destroy to Container::destroy_range
Because Visual Studio C++17 compiler occurred error C2668.
This compiler said Container::destroy and std::destroy are ambiguous.